### PR TITLE
Refactor/cleanup python module

### PR DESCRIPTION
**Pull request by laserson**
This is a general refactoring of the Python module that @schristley submitted.  It removes unnecessary imports, simplifies the structure somewhat, uses versioneer for versioning, and brings style in line with PEP8/Google.  @schristley, please check it out, and if it looks good, I'll merge.  AFAICT, the functionality should be the same as before.

### CODE REVIEW

**Comment by laserson** [comment]
(note: the patch looks big but that's only bc of checking in the versioneer stuff, which you can happily ignore)

**Comment by laserson** [comment]
sigh...I installed fresh and now the import itself breaks...will have to submit some more changes

**Comment by laserson** [comment]
Ok, now this appears good-to-go

**Comment by schristley** [comment]
thanks @laserson , will check it out once I get back from my trip.

**Pull request merged**
